#!/usr/bin/env python3
"""Deterministic helpers for the spec-to-tasks markdown task store.

Zero external dependencies (stdlib only). Task files are markdown with a small YAML-ish
frontmatter block; this script reads that frontmatter to compute ids, rebuild the overview
table, and validate the dependency graph. See ../references/task-format.md for the schema.

Subcommands:
    next-id     Print the next unused task id (max id + 1, or 1 if empty).
    overview    Regenerate <tasks-dir>/overview.md from every task file.
    validate    Check that dependencies exist, point only to lower ids, and form no cycle.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Files inside the tasks dir that are generated, not tasks themselves.
GENERATED = {"overview.md", "complexity-report.md"}

SUBTASK_HEADING = re.compile(r"^###\s+(\d+)\.(\d+)\b", re.MULTILINE)


class TaskError(Exception):
    """Raised for malformed task files or an invalid dependency graph."""


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Split leading ``---`` frontmatter from a markdown document.

    Args:
        text: Full file contents.

    Returns:
        A tuple of (frontmatter dict of raw string values, body text). If no frontmatter
        block is present, the dict is empty and body is the original text.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, text
    fm: dict[str, str] = {}
    for line in lines[1:end]:
        if not line.strip() or ":" not in line:
            continue
        key, _, val = line.partition(":")
        fm[key.strip()] = val.strip()
    return fm, "\n".join(lines[end + 1 :])


def _parse_int(value: str | None) -> int | None:
    """Parse an optional integer field; blank/absent yields None."""
    if value is None or value == "":
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _parse_deps(value: str | None) -> list[int]:
    """Parse a ``dependencies`` field like ``[1, 3]`` or ``1, 3`` into a list of ints."""
    if not value:
        return []
    inner = value.strip().lstrip("[").rstrip("]").strip()
    if not inner:
        return []
    deps = []
    for part in inner.split(","):
        part = part.strip()
        if part:
            deps.append(int(part))
    return deps


class Task:
    """A single parsed task file."""

    def __init__(self, path: Path, fm: dict[str, str], body: str):
        if "id" not in fm:
            raise TaskError(f"{path.name}: missing 'id' in frontmatter")
        try:
            self.id = int(fm["id"])
        except ValueError as exc:
            raise TaskError(f"{path.name}: non-integer id {fm['id']!r}") from exc
        self.path = path
        self.title = fm.get("title", "").strip()
        self.status = fm.get("status", "").strip() or "pending"
        self.priority = fm.get("priority", "").strip() or "medium"
        self.dependencies = _parse_deps(fm.get("dependencies"))
        self.complexity = _parse_int(fm.get("complexity"))
        self.subtask_count = len(SUBTASK_HEADING.findall(body))


def load_tasks(tasks_dir: Path) -> list[Task]:
    """Load and parse every task file in ``tasks_dir``, sorted by id.

    Raises:
        TaskError: If a file is malformed or two tasks share an id.
    """
    if not tasks_dir.is_dir():
        raise TaskError(f"tasks directory not found: {tasks_dir}")
    tasks: list[Task] = []
    for path in sorted(tasks_dir.glob("*.md")):
        if path.name in GENERATED:
            continue
        fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            continue  # not a task file
        tasks.append(Task(path, fm, body))
    tasks.sort(key=lambda t: t.id)
    seen: dict[int, str] = {}
    for t in tasks:
        if t.id in seen:
            raise TaskError(f"duplicate id {t.id}: {seen[t.id]} and {t.path.name}")
        seen[t.id] = t.path.name
    return tasks


def cmd_next_id(tasks_dir: Path) -> int:
    """Print the next unused id and return an exit code."""
    try:
        tasks = load_tasks(tasks_dir)
    except TaskError:
        # An empty/absent dir just means we start at 1.
        print(1)
        return 0
    print((max((t.id for t in tasks), default=0)) + 1)
    return 0


def cmd_overview(tasks_dir: Path) -> int:
    """Regenerate ``overview.md`` and return an exit code."""
    tasks = load_tasks(tasks_dir)
    lines = [
        "# Task overview",
        "",
        f"{len(tasks)} task(s). Generated by `scripts/tasks.py overview` — do not edit by hand.",
        "",
        "| ID | Title | Status | Priority | Depends on | Complexity | Subtasks |",
        "|----|-------|--------|----------|------------|------------|----------|",
    ]
    for t in tasks:
        deps = ", ".join(str(d) for d in t.dependencies) or "—"
        cx = str(t.complexity) if t.complexity is not None else "—"
        subs = str(t.subtask_count) if t.subtask_count else "—"
        lines.append(
            f"| {t.id} | {t.title} | {t.status} | {t.priority} | {deps} | {cx} | {subs} |"
        )
    out = tasks_dir / "overview.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(tasks)} tasks)")
    return 0


def cmd_validate(tasks_dir: Path) -> int:
    """Validate the dependency graph. Return 0 if sound, 1 otherwise."""
    tasks = load_tasks(tasks_dir)
    ids = {t.id for t in tasks}
    errors: list[str] = []

    for t in tasks:
        for d in t.dependencies:
            if d not in ids:
                errors.append(f"task {t.id} ({t.path.name}): depends on missing id {d}")
            elif d >= t.id:
                errors.append(
                    f"task {t.id} ({t.path.name}): depends on id {d} which is not lower "
                    f"(dependencies must point to earlier tasks)"
                )

    # Cycle detection via DFS over the dependency edges.
    graph = {t.id: [d for d in t.dependencies if d in ids] for t in tasks}
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {i: WHITE for i in ids}

    def visit(node: int, stack: list[int]) -> None:
        color[node] = GRAY
        for nxt in graph.get(node, []):
            if color[nxt] == GRAY:
                cycle = stack[stack.index(nxt):] + [nxt]
                errors.append("dependency cycle: " + " -> ".join(str(c) for c in cycle))
            elif color[nxt] == WHITE:
                visit(nxt, stack + [nxt])
        color[node] = BLACK

    for i in sorted(ids):
        if color[i] == WHITE:
            visit(i, [i])

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        print(f"{len(errors)} validation error(s)", file=sys.stderr)
        return 1
    print(f"ok: {len(tasks)} tasks, dependency graph is valid")
    return 0


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "command", choices=["next-id", "overview", "validate"], help="operation to run"
    )
    parser.add_argument(
        "--tasks-dir",
        default="tasks",
        help="directory holding task markdown files (default: ./tasks)",
    )
    args = parser.parse_args(argv)
    tasks_dir = Path(args.tasks_dir)

    try:
        if args.command == "next-id":
            return cmd_next_id(tasks_dir)
        if args.command == "overview":
            return cmd_overview(tasks_dir)
        if args.command == "validate":
            return cmd_validate(tasks_dir)
    except TaskError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
