// Generates and replaces the machine-owned Child Docs Index block. This is the
// J2 job: the index is a pure function of the directory tree, regenerated by
// `dox sync` and never hand-edited between the markers.
import { existsSync, readdirSync, statSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { Config, INDEX_CLOSE, INDEX_HEADING, INDEX_OPEN } from "./config.js";
import { codeFiles, dirHasCode, hasScopedDescendant, isExcluded, isPerfileDir } from "./scope.js";
import { summaryOf } from "./summary.js";

interface Area {
  name: string;
  summary: string;
  documented: boolean;
}

/** Immediate child subareas of d that are themselves in scope. */
function childAreas(d: string, root: string, cfg: Config): Area[] {
  const doc = cfg.doc_name;
  const out: Area[] = [];
  let children: string[];
  try {
    children = readdirSync(d)
      .filter((name) => {
        try { return statSync(join(d, name)).isDirectory(); } catch { return false; }
      })
      .sort();
  } catch {
    return out;
  }
  for (const name of children) {
    const c = join(d, name);
    if (isExcluded(relative(root, c), cfg)) continue;
    const hasDoc = existsSync(join(c, doc));
    if (hasDoc || dirHasCode(c, cfg) || hasScopedDescendant(c, root, cfg)) {
      out.push({ name, summary: hasDoc ? summaryOf(join(c, doc)) : "", documented: hasDoc });
    }
  }
  return out;
}

export function genIndex(d: string, root: string, cfg: Config): string {
  const doc = cfg.doc_name;
  const lines = [INDEX_OPEN, "<!-- generated by `dox sync` - do not edit by hand -->", INDEX_HEADING];
  const body: string[] = [];

  // Sub-domains (child folders).
  for (const { name, summary, documented } of childAreas(d, root, cfg)) {
    const link = documented ? `[\`${name}/\`](${name}/${doc})` : `\`${name}/\``;
    const tail = summary ? ` - ${summary}` : (!documented ? " - _(undocumented)_" : "");
    body.push(`- ${link}${tail}`);
  }

  // Per-file docs, when this folder opts into per-file documentation.
  if (isPerfileDir(d, cfg)) {
    for (const f of codeFiles(d, cfg)) {
      const name = basename(f);
      if (existsSync(join(d, `${name}.md`))) {
        body.push(`- [\`${name}\`](${name}.md) - ${summaryOf(join(d, `${name}.md`))}`.replace(/[ -]+$/, ""));
      } else {
        body.push(`- \`${name}\` - _(undocumented)_`);
      }
    }
  }

  if (body.length === 0) body.push("_Leaf domain - no children._");
  lines.push(...body, INDEX_CLOSE);
  return lines.join("\n");
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Markers are only recognised when alone on their own line, so prose that
// merely mentions the marker string (e.g. in a rules bullet) is never matched.
const INDEX_BLOCK_RE = new RegExp(
  "^[ \\t]*" + escapeRe(INDEX_OPEN) + "[ \\t]*$[\\s\\S]*?^[ \\t]*" + escapeRe(INDEX_CLOSE) + "[ \\t]*$",
  "m",
);

export function replaceIndex(text: string, block: string): string {
  if (INDEX_BLOCK_RE.test(text)) {
    return text.replace(INDEX_BLOCK_RE, () => block);
  }
  const sep = text.endsWith("\n\n") ? "" : text.endsWith("\n") ? "\n" : "\n\n";
  return text + sep + block + "\n";
}
